### ISSUE TITLE
Замечания по программе Dictionary

### ISSUE THREAD

**Issue by alexey-malov** [AlexanderFadeev/oop#11]
```
Как дела?
Неизвестное слово "Как дела?". Введите перевод или пустую строку для отказа
how are you?
"Как дела?" is not a valid english collocation
```
- [x] Не надо спрашивать перевод невалидных английских слов. Либо не делать проверок на допустимость используемых символов

**Comment by alexey-malov** [comment]
- [x] CFileDictionary зря наследуется от CDictionary. Класс CDictionary не предназначен для наследования:
- у него нет виртуального деструктора
- у него нет виртуальных методов
- наследование от конкретных классов редко бывает правильным
- CFileDictionary нарушает Single Responsibility Principle.

**Comment by alexey-malov** [comment]
```c++
	static bool IsRussian(const std::string word);
	static bool IsEnglish(const std::string word);
```
- [x] объекты следует передавать по константной ссылке, если функция не модифицирует их состояние.
Примитивные объекты передавать по константной ссылке выгоды нет, лучше по значению

**Comment by alexey-malov** [comment]
```c++
			AND_WHEN("Sample word is added")
			{
				THEN("Sample word can be found")
				{
					dict.Add("Cat", "Кот");
					REQUIRE(dict.Has("Cat"));
```

- [x] dict.Add следует поднять выше

**Comment by AniSkyWorker** [comment]
- [ ] ```CDictionaryControl``` лучше переименовать в ```Controller```
- [ ] стоит убрать из словаря метода по считыванию и записи в файл, пусть в нем будет геттер для контейнера, т.к. он уже отвечает за состояние словаря, хуже не станет, если он будет уметь пользоваться его данными.
