### ISSUE TITLE
Замечания по программе "Калькулятор"

### ISSUE THREAD

**Issue by alexey-malov** [AlexanderFadeev/oop#12]
- [x] Виртуальные методы базового класса можно объявить приватными, если их вызывает только сам класс. Наследники смогут их переопределить, но не смогут вызывать самостоятельно

**Comment by alexey-malov** [comment]
- [x] Какая-то излишняя мешанина с mutable-полями. определённо, коллекции не должны быть mutable-полями

**Comment by alexey-malov** [comment]
- [x] с optional код может стать чуточку проще

**Comment by alexey-malov** [comment]
- [ ] Нельзя просто так использовать результат lock у weak_ptr

```c++
if (auto sp = wp.lock())
{
    sp->DoSomething();
}
```

**Comment by AniSkyWorker** [comment]
- [ ] шаблонные приватные функции в ```CCalculator``` - чисто утилитарные, удобно, чтобы не раздувать декларацию класса, будет вынести их в cpp или хотя бы объявить статичными
```c++
//пример декларации в *.cpp в безымянном namespace
namespace
{
void DoSomething(...)
{
    //do something...
}
}

**Comment by alexey-malov** [comment]
- [x] Конструктор в классе CFunction сделать приватным. В методе New использовать new + оборачивание в shared_ptr вместо make_shared

- [x] Сделать 2 версии метода New вместо одного шаблонного
