### ISSUE TITLE
Замечания по программе "Shapes" В-2

### ISSUE THREAD

**Issue by AniSkyWorker** [AlexanderFadeev/oop#13]
- [ ] Интерфейсы нужно делать простыми, без содержания логики, если есть общее поведение, оно выделяется в базовый класс (CShape, CAbstractShape и т.п.) Касается ```IShape``` и ```ISolidShape```
- [ ] лучше явно писать nullptr, вместо прямой инициализации

**Comment by alexey-malov** [comment]
- [x] При изменении размеров окна картинка пропадает.
- [ ] При вертикальном ресайзе картинка смещается

**Comment by alexey-malov** [comment]
- [x] Почитайте про принцип инверсии зависимостей, а также лекцию по паттерну "Шаблонный метод (Templace Method)" у меня в репозитории ood. Неправильно, когда алгоритм конвертирования в строку реализуется в каждом из классов-наследников.

**Comment by alexey-malov** [comment]
- [x] ShapeFactory не должен держать istream. Надо, чтобы в фабрике метод создания фигуры принимал строку и возвращал фигуру. Создание массивов фигур выходит за область ответственности фабрики. 

- [x] Методы фабрики должны начинаться с Create, а не с Get
