### ISSUE TITLE
Замечания по программе HTTPURL

### ISSUE THREAD

**Issue by oMystique** [AlexanderFadeev/oop#16]
- [x] PROTOCOL_DEFAULT_PORT**S**

- [x] Лучше перемазывать PROTOCOL_TO_STRING в PROTOCOL_STRING_REPRESENTATIONS

- [x] Возможно стоит сделать конструктор приватным в классе URLParsingError

**Comment by alexey-malov** [comment]
```c++
class CUrlParsingError
	: public std::invalid_argument
{
public:
	static CUrlParsingError PortOutOfRange();
	static CUrlParsingError InvalidURL(const std::string& url);
	static CUrlParsingError InvalidProtocol(const std::string& protocol);
	static CUrlParsingError InvalidDomain(const std::string& domain);
	static CUrlParsingError InvalidPort(const std::string& port);
	static CUrlParsingError InvalidPort(uint16_t port);

private:
	CUrlParsingError(const std::string& message);
};
```

- [ ] Выпилить статические методы и выбрасывать в CHttpUrl-е экземплятры исключений

**Comment by alexey-malov** [comment]
- [ ] В процессе взаимодействия с пользователем программа должна выводить строковое представление URL-а, полученного от HttpURL. Убедиться, что порт, совпадающий дефолтныи для протокола, не выводится

**Comment by oMystique** [comment]
- [x] Для хранение строковых представлений ошибок лучше завести std::map, где ключем будет являться enum-представление ошибки, а значением - строковое. Это нужно для того, чтобы при внесении изменений в текст ошибки, не приходилось эти изменения применять везде (а что-нибудь может забыться)
